name: q_task
description: A clean task management app that saves tasks in markdown.
publish_to: none

version: 0.9.5

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  path_provider: ^2.1.0
  uuid: ^4.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  spell_check_on_client: ^1.0.0
  package_info_plus: ^8.0.0
  window_manager: ^0.4.0
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  markdown_quill: ^4.3.0
  desktop_drop: ^0.4.0
  cross_file: ^0.3.0
  path: ^1.8.3
  markdown: ^7.2.0
  archive: ^4.0.7
  file_selector: ^1.0.4
  url_launcher: ^6.3.2
  macos_secure_bookmarks: ^0.2.1
  share_plus: ^12.0.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.3
  google_sign_in_all_platforms: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dictionaries/en_words.txt
    - assets/dictionaries/es_words.txt
    - assets/dictionaries/hunspell/en_US.dic
    - assets/dictionaries/hunspell/en_US.aff
    - assets/dictionaries/hunspell/es_ES.dic
    - assets/dictionaries/hunspell/es_ES.aff
